"use client"

import { useState } from "react"
import type { Product } from "@/types/product"

const mockProducts: Product[] = [
  // Смартфоны (4 товара)
  {
    id: "1",
    name: "iPhone 15 Pro",
    brand: "Apple",
    category: "Смартфоны",
    price: 89990,
    rating: 4.8,
    reviewCount: 1250,
    inStock: true,
    description: "Профессиональный смартфон с титановым корпусом и камерой Pro",
    images: [
      "https://images.unsplash.com/photo-1592750475338-74b7b21085ab?w=400&h=400&fit=crop",
      "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=400&h=400&fit=crop",
      "https://images.unsplash.com/photo-1580910051074-3eb694886505?w=400&h=400&fit=crop",
    ],
    specifications: {
      "Диагональ экрана": '6.1"',
      Процессор: "A17 Pro",
      "Оперативная память": "8 ГБ",
      "Встроенная память": "128 ГБ",
      Камера: "48 Мп",
      Батарея: "3274 мАч",
      "Операционная система": "iOS 17",
      "Материал корпуса": "Титан",
      Защита: "IP68",
    },
  },
  {
    id: "2",
    name: "Samsung Galaxy S24 Ultra",
    brand: "Samsung",
    category: "Смартфоны",
    price: 94990,
    rating: 4.7,
    reviewCount: 890,
    inStock: true,
    description: "Флагманский смартфон с S Pen и камерой 200 Мп",
    images: [
      "https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?w=400&h=400&fit=crop",
      "https://images.unsplash.com/photo-1574944985070-8f3ebc6b79d2?w=400&h=400&fit=crop",
    ],
    specifications: {
      "Диагональ экрана": '6.8"',
      Процессор: "Snapdragon 8 Gen 3",
      "Оперативная память": "12 ГБ",
      "Встроенная память": "256 ГБ",
      Камера: "200 Мп",
      Батарея: "5000 мАч",
      "Операционная система": "Android 14",
      "Материал корпуса": "Алюминий",
      Защита: "IP68",
    },
  },
  {
    id: "3",
    name: "Google Pixel 8 Pro",
    brand: "Google",
    category: "Смартфоны",
    price: 79990,
    rating: 4.6,
    reviewCount: 654,
    inStock: true,
    description: "Смартфон с чистым Android и лучшей камерой для фото",
    images: ["https://images.unsplash.com/photo-1567581935884-3349723552ca?w=400&h=400&fit=crop"],
    specifications: {
      "Диагональ экрана": '6.7"',
      Процессор: "Google Tensor G3",
      "Оперативная память": "12 ГБ",
      "Встроенная память": "128 ГБ",
      Камера: "50 Мп",
      Батарея: "5050 мАч",
      "Операционная система": "Android 14",
      "Материал корпуса": "Алюминий",
      Защита: "IP68",
    },
  },
  {
    id: "4",
    name: "Xiaomi 14 Ultra",
    brand: "Xiaomi",
    category: "Смартфоны",
    price: 69990,
    rating: 4.5,
    reviewCount: 432,
    inStock: true,
    description: "Флагман с камерой Leica и быстрой зарядкой 90W",
    images: [
      "https://images.unsplash.com/photo-1574944985070-8f3ebc6b79d2?w=400&h=400&fit=crop",
      "https://images.unsplash.com/photo-1567581935884-3349723552ca?w=400&h=400&fit=crop",
    ],
    specifications: {
      "Диагональ экрана": '6.73"',
      Процессор: "Snapdragon 8 Gen 3",
      "Оперативная память": "12 ГБ",
      "Встроенная память": "256 ГБ",
      Камера: "50 Мп",
      Батарея: "5300 мАч",
      "Операционная система": "MIUI 15",
      "Материал корпуса": "Керамика",
      Защита: "IP68",
    },
  },

  // Ноутбуки (4 товара)
  {
    id: "5",
    name: "MacBook Air M3",
    brand: "Apple",
    category: "Ноутбуки",
    price: 134990,
    rating: 4.9,
    reviewCount: 567,
    inStock: true,
    description: "Ультратонкий ноутбук с процессором M3 и 18 часами автономной работы",
    images: [
      "https://images.unsplash.com/photo-1541807084-5c52b6b3adef?w=400&h=400&fit=crop",
      "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=400&h=400&fit=crop",
    ],
    specifications: {
      "Диагональ экрана": '13.6"',
      Процессор: "Apple M3",
      "Оперативная память": "8 ГБ",
      "Встроенная память": "256 ГБ SSD",
      Графика: "8-ядерный GPU",
      Вес: "1.24 кг",
      "Операционная система": "macOS Sonoma",
      "Время работы": "18 часов",
      Порты: "2x Thunderbolt",
    },
  },
  {
    id: "6",
    name: "Dell XPS 13",
    brand: "Dell",
    category: "Ноутбуки",
    price: 89990,
    rating: 4.5,
    reviewCount: 423,
    inStock: false,
    description: "Компактный ноутбук премиум-класса с процессором Intel",
    images: ["https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?w=400&h=400&fit=crop"],
    specifications: {
      "Диагональ экрана": '13.4"',
      Процессор: "Intel Core i7-1360P",
      "Оперативная память": "16 ГБ",
      "Встроенная память": "512 ГБ SSD",
      Графика: "Intel Iris Xe",
      Вес: "1.19 кг",
      "Операционная система": "Windows 11",
      "Время работы": "12 часов",
      Порты: "2x USB-C, 1x USB-A",
    },
  },
  {
    id: "7",
    name: "ASUS ROG Zephyrus G14",
    brand: "ASUS",
    category: "Ноутбуки",
    price: 159990,
    rating: 4.7,
    reviewCount: 789,
    inStock: true,
    description: "Игровой ноутбук с RTX 4070 и процессором AMD Ryzen",
    images: [
      "https://images.unsplash.com/photo-1603302576837-37561b2e2302?w=400&h=400&fit=crop",
      "https://images.unsplash.com/photo-1525547719571-a2d4ac8945e2?w=400&h=400&fit=crop",
    ],
    specifications: {
      "Диагональ экрана": '14"',
      Процессор: "AMD Ryzen 9 7940HS",
      "Оперативная память": "32 ГБ",
      "Встроенная память": "1 ТБ SSD",
      Графика: "RTX 4070",
      Вес: "1.65 кг",
      "Операционная система": "Windows 11",
      "Время работы": "8 часов",
      Порты: "2x USB-C, 2x USB-A, HDMI",
    },
  },
  {
    id: "8",
    name: "Lenovo ThinkPad X1 Carbon",
    brand: "Lenovo",
    category: "Ноутбуки",
    price: 179990,
    rating: 4.6,
    reviewCount: 345,
    inStock: true,
    description: "Бизнес-ноутбук с защищенным корпусом и долгой автономностью",
    images: ["https://images.unsplash.com/photo-1484788984921-03950022c9ef?w=400&h=400&fit=crop"],
    specifications: {
      "Диагональ экрана": '14"',
      Процессор: "Intel Core i7-1365U",
      "Оперативная память": "16 ГБ",
      "Встроенная память": "512 ГБ SSD",
      Графика: "Intel Iris Xe",
      Вес: "1.12 кг",
      "Операционная система": "Windows 11 Pro",
      "Время работы": "15 часов",
      Порты: "2x USB-C, 2x USB-A, HDMI",
    },
  },

  // Наушники (4 товара)
  {
    id: "9",
    name: "Sony WH-1000XM5",
    brand: "Sony",
    category: "Наушники",
    price: 29990,
    rating: 4.6,
    reviewCount: 789,
    inStock: true,
    description: "Беспроводные наушники с активным шумоподавлением",
    images: [
      "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400&h=400&fit=crop",
      "https://images.unsplash.com/photo-1583394838336-acd977736f90?w=400&h=400&fit=crop",
    ],
    specifications: {
      Тип: "Накладные",
      Подключение: "Bluetooth 5.2",
      Шумоподавление: "Активное",
      "Время работы": "30 часов",
      "Быстрая зарядка": "3 мин = 3 часа",
      Вес: "250 г",
      "Поддержка кодеков": "LDAC, AAC, SBC",
      "Частотный диапазон": "4 Гц - 40 кГц",
    },
  },
  {
    id: "10",
    name: "AirPods Pro 2",
    brand: "Apple",
    category: "Наушники",
    price: 24990,
    rating: 4.7,
    reviewCount: 1100,
    inStock: true,
    description: "Беспроводные наушники с адаптивным шумоподавлением",
    images: [
      "https://images.unsplash.com/photo-1572569511254-d8f925fe2cbb?w=400&h=400&fit=crop",
      "https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=400&h=400&fit=crop",
    ],
    specifications: {
      Тип: "Внутриканальные",
      Подключение: "Bluetooth 5.3",
      Шумоподавление: "Адаптивное",
      "Время работы": "6 часов + 24 часа с кейсом",
      "Быстрая зарядка": "5 мин = 1 час",
      Вес: "5.3 г (каждый)",
      "Поддержка кодеков": "AAC",
      "Частотный диапазон": "20 Гц - 20 кГц",
    },
  },
  {
    id: "11",
    name: "Bose QuietComfort Ultra",
    brand: "Bose",
    category: "Наушники",
    price: 34990,
    rating: 4.5,
    reviewCount: 456,
    inStock: true,
    description: "Премиальные наушники с лучшим шумоподавлением",
    images: [
      "https://images.unsplash.com/photo-1484704849700-f032a568e944?w=400&h=400&fit=crop",
      "https://images.unsplash.com/photo-1545127398-14699f92334b?w=400&h=400&fit=crop",
    ],
    specifications: {
      Тип: "Накладные",
      Подключение: "Bluetooth 5.3",
      Шумоподавление: "Активное",
      "Время работы": "24 часа",
      "Быстрая зарядка": "15 мин = 2.5 часа",
      Вес: "254 г",
      "Поддержка кодеков": "AAC, SBC",
      "Частотный диапазон": "20 Гц - 20 кГц",
    },
  },
  {
    id: "12",
    name: "Sennheiser Momentum 4",
    brand: "Sennheiser",
    category: "Наушники",
    price: 27990,
    rating: 4.4,
    reviewCount: 234,
    inStock: false,
    description: "Аудиофильские наушники с превосходным звуком",
    images: ["https://images.unsplash.com/photo-1487215078519-e21cc028cb29?w=400&h=400&fit=crop"],
    specifications: {
      Тип: "Накладные",
      Подключение: "Bluetooth 5.2",
      Шумоподавление: "Адаптивное",
      "Время работы": "60 часов",
      "Быстрая зарядка": "10 мин = 6 часов",
      Вес: "293 г",
      "Поддержка кодеков": "aptX, AAC, SBC",
      "Частотный диапазон": "6 Гц - 22 кГц",
    },
  },

  // Планшеты (4 товара)
  {
    id: "13",
    name: "iPad Pro 12.9 M2",
    brand: "Apple",
    category: "Планшеты",
    price: 109990,
    rating: 4.8,
    reviewCount: 678,
    inStock: true,
    description: "Профессиональный планшет с процессором M2 и Liquid Retina дисплеем",
    images: [
      "https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=400&h=400&fit=crop",
      "https://images.unsplash.com/photo-1561154464-82e9adf32764?w=400&h=400&fit=crop",
    ],
    specifications: {
      "Диагональ экрана": '12.9"',
      Процессор: "Apple M2",
      "Оперативная память": "8 ГБ",
      "Встроенная память": "128 ГБ",
      "Тип дисплея": "Liquid Retina XDR",
      Камера: "12 Мп",
      Вес: "682 г",
      "Операционная система": "iPadOS 17",
      "Время работы": "10 часов",
    },
  },
  {
    id: "14",
    name: "Samsung Galaxy Tab S9 Ultra",
    brand: "Samsung",
    category: "Планшеты",
    price: 89990,
    rating: 4.6,
    reviewCount: 345,
    inStock: true,
    description: "Большой планшет с S Pen и AMOLED дисплеем",
    images: ["/images/samsung-tab-s9-ultra.png"],
    specifications: {
      "Диагональ экрана": '14.6"',
      Процессор: "Snapdragon 8 Gen 2",
      "Оперативная память": "12 ГБ",
      "Встроенная память": "256 ГБ",
      "Тип дисплея": "Dynamic AMOLED 2X",
      Камера: "13 Мп",
      Вес: "732 г",
      "Операционная система": "Android 13",
      "Время работы": "14 часов",
    },
  },
  {
    id: "15",
    name: "Microsoft Surface Pro 9",
    brand: "Microsoft",
    category: "Планшеты",
    price: 119990,
    rating: 4.4,
    reviewCount: 234,
    inStock: false,
    description: "Планшет-трансформер с полноценной Windows",
    images: ["/images/surface-pro-9.png"],
    specifications: {
      "Диагональ экрана": '13"',
      Процессор: "Intel Core i5-1235U",
      "Оперативная память": "8 ГБ",
      "Встроенная память": "256 ГБ SSD",
      "Тип дисплея": "PixelSense Flow",
      Камера: "10 Мп",
      Вес: "879 г",
      "Операционная система": "Windows 11",
      "Время работы": "15.5 часов",
    },
  },
  {
    id: "16",
    name: "Xiaomi Pad 6",
    brand: "Xiaomi",
    category: "Планшеты",
    price: 34990,
    rating: 4.3,
    reviewCount: 567,
    inStock: true,
    description: "Доступный планшет с качественным дисплеем и металлическим корпусом",
    images: ["https://images.unsplash.com/photo-1585790050230-5dd28404ccb9?w=400&h=400&fit=crop"],
    specifications: {
      "Диагональ экрана": '11"',
      Процессор: "Snapdragon 870",
      "Оперативная память": "6 ГБ",
      "Встроенная память": "128 ГБ",
      "Тип дисплея": "IPS LCD",
      Камера: "13 Мп",
      Вес: "490 г",
      "Операционная система": "MIUI Pad 14",
      "Время работы": "12 часов",
    },
  },
]

export function useProducts() {
  const [products] = useState<Product[]>(mockProducts)

  const categories = Array.from(new Set(products.map((p) => p.category)))
  const brands = Array.from(new Set(products.map((p) => p.brand)))

  return {
    products,
    categories,
    brands,
  }
}
